# Configurations related to the theme of Streamlit apps.
[theme]

# Base theme [“light”, “dark”]
base="light"

# Primary color used in the main interactive elements
primaryColor="#81879e"

# Background color for the main content area
backgroundColor="#ffffff"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor="#66a1c5"

# Color used for almost all text
textColor="#272729"

# Any other options you wish to specify...
